version: '3.8'

services:
  azure-pipelines-agent:
    image: 'azure-pipelines-agent'
    build:
      context: './build'
    restart: 'unless-stopped'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      AZP_URL: '${AZP_URL}'
      AZP_TOKEN: '${AZP_TOKEN}'
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
