version: '3.8'

services:
  pihole:
    container_name: 'pihole'
    image: 'pihole/pihole:latest'
    restart: 'unless-stopped'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - './.data/pihole/:/etc/pihole/'
      - './.data/pihole-dnsmasq/:/etc/dnsmasq.d/'
      - './pihole/resolv.conf:/etc/resolv.conf'
      - './pihole/adlists.list:/etc/pihole/adlists.list'
    environment:
      TZ: 'Europe/Zurich'
      DNSSEC: 'True'
      DNS1: '1.0.0.1'
      DNS2: '1.1.1.1'
      WEBPASSWORD: 'secure'
