version: '3.8'

services:
  traefik:
    extends:
      file: 'traefik/service.yml'
      service: 'traefik'

  pihole:
    extends:
      file: 'pihole/service.yml'
      service: 'pihole'

  dozzle:
    extends:
      file: 'dozzle/service.yml'
      service: 'dozzle'

  portainer:
    extends:
      file: 'portainer/service.yml'
      service: 'portainer'

  watchtower:
    extends:
      file: 'watchtower/service.yml'
      service: 'watchtower'

  prometheus:
    extends:
      file: 'prometheus/service.yml'
      service: 'prometheus'
    depends_on:
      - 'blackbox-exporter'
      - 'speedtest-exporter'
      - 'pihole-exporter'

  blackbox-exporter:
    extends:
      file: 'prometheus/service.yml'
      service: 'blackbox-exporter'

  speedtest-exporter:
    extends:
      file: 'prometheus/service.yml'
      service: 'speedtest-exporter'

  pihole-exporter:
    extends:
      file: 'prometheus/service.yml'
      service: 'pihole-exporter'
    depends_on:
      - 'pihole'

  gitea:
    extends:
      file: 'gitea/service.yml'
      service: 'gitea'
    depends_on:
      - 'gitea-db'

  gitea-db:
    extends:
      file: 'gitea/service.yml'
      service: 'gitea-db'

  home-assistant:
    extends:
      file: 'home-assistant/service.yml'
      service: 'home-assistant'
    depends_on:
      - 'home-assistant-db'

  home-assistant-db:
    extends:
      file: 'home-assistant/service.yml'
      service: 'home-assistant-db'

  adminer:
    extends:
      file: 'adminer/service.yml'
      service: 'adminer'
    environment:
      MYSQL_SERVERS: 'gitea-db,home-assistant-db'
    depends_on:
      - 'gitea-db'
      - 'home-assistant-db'

  grafana:
    extends:
      file: 'grafana/service.yml'
      service: 'grafana'

  ofelia:
    extends:
      file: 'ofelia/service.yml'
      service: 'ofelia'

  dashboard:
    extends:
      file: 'dashboard/service.yml'
      service: 'dashboard'
