version: '3.8'

services:
  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    restart: 'unless-stopped'
    ports:
      - '80:80'
    volumes:
      - './nginx/:/etc/nginx/conf.d/'
    depends_on:
      - 'pihole'
      - 'phpmyadmin'
      - 'home-assistant'

  pihole:
    container_name: 'pihole'
    image: 'pihole/pihole:latest'
    restart: 'unless-stopped'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      # - '80:80/tcp' available through reverse proxy
      - '443:443/tcp'
    volumes:
      - './.data/pihole/:/etc/pihole/'
      - './.data/pihole-dnsmasq/:/etc/dnsmasq.d/'
      - './pihole/resolv.conf:/etc/resolv.conf'
      - './pihole/adlists.list:/etc/pihole/adlists.list'
      - './pihole/custom.list:/etc/pihole/custom.list'
    environment:
      TZ: '${TIMEZONE}'
      DNSSEC: 'True'
      DNS1: '1.0.0.1'
      DNS2: '1.1.1.1'
      WEBPASSWORD: '${PIHOLE_PASSWORD}'

  home-assistant:
    container_name: 'home-assistant'
    image: 'homeassistant/home-assistant:stable'
    restart: 'unless-stopped'
    # ports:
    # - '8123:8123' available through reverse proxy
    volumes:
      - './.data/home-assistant/:/config/'
      - './home-assistant/configuration.yaml:/config/configuration.yaml'
    environment:
      TZ: '${TIMEZONE}'
      DATABASE_CONNECTION: 'mysql://homeassistant:${HA_MYSQL_PASSWORD}@home-assistant-db/homeassistant_db?charset=utf8'
    depends_on:
      - 'home-assistant-db'

  home-assistant-db:
    container_name: 'home-assistant-db'
    image: 'mysql:latest'
    restart: 'unless-stopped'
    volumes:
      - './.data/home-assistant-db/:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'homeassistant_db'
      MYSQL_USER: 'homeassistant'
      MYSQL_PASSWORD: '${HA_MYSQL_PASSWORD}'

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin:latest'
    restart: 'unless-stopped'
    # ports:
    # - '80:80' available through reverse proxy
    environment:
      PMA_HOSTS: 'home-assistant-db'
    depends_on:
      - 'home-assistant-db'
