version: '3.8'

services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:latest'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik/:/etc/traefik/:ro'
      - '${CERT_DIR:?err}/:/etc/certs/:ro'
      - '${LOG_DIR:?err}/traefik/:/var/log/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls=true'

  pihole:
    container_name: 'pihole'
    image: 'pihole/pihole:latest'
    restart: 'unless-stopped'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
    volumes:
      - '${DATA_DIR:?err}/pihole/:/etc/pihole/'
      - '${DATA_DIR:?err}/pihole-dnsmasq/:/etc/dnsmasq.d/'
      - './pihole/resolv.conf:/etc/resolv.conf:ro'
      - './pihole/adlists.list:/etc/pihole/adlists.list:ro'
      - './pihole/custom.list:/etc/pihole/custom.list:ro'
    environment:
      ServerIP: ${LOCAL_IP}
      TZ: '${TIMEZONE}'
      DNSSEC: 'True'
      DNS1: '1.0.0.1'
      DNS2: '1.1.1.1'
      WEBPASSWORD: '${PIHOLE_PASSWORD}'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.pihole.loadbalancer.server.port=80'
      - 'traefik.http.routers.pihole.entrypoints=websecure'
      - 'traefik.http.routers.pihole.tls=true'
