version: '3.8'

services:
  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    restart: 'unless-stopped'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/:/etc/nginx/conf.d/'
      - './certificates/:/etc/ssl/'
    depends_on:
      - 'pihole'
      - 'phpmyadmin'
      - 'home-assistant'

  home-assistant:
    container_name: 'home-assistant'
    image: 'homeassistant/home-assistant:stable'
    restart: 'unless-stopped'
    # ports:
    # - '8123:8123' available through reverse proxy
    volumes:
      - './.data/home-assistant/:/config/'
      - './home-assistant/configuration.yaml:/config/configuration.yaml'
    environment:
      TZ: '${TIMEZONE}'
      DATABASE_CONNECTION: 'mysql://homeassistant:${HA_MYSQL_PASSWORD}@home-assistant-db/homeassistant_db?charset=utf8'
    depends_on:
      - 'home-assistant-db'

  home-assistant-db:
    container_name: 'home-assistant-db'
    image: 'mysql:latest'
    restart: 'unless-stopped'
    volumes:
      - './.data/home-assistant-db/:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'homeassistant_db'
      MYSQL_USER: 'homeassistant'
      MYSQL_PASSWORD: '${HA_MYSQL_PASSWORD}'

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin:latest'
    restart: 'unless-stopped'
    # ports:
    # - '80:80' available through reverse proxy
    environment:
      PMA_HOSTS: 'home-assistant-db'
    depends_on:
      - 'home-assistant-db'

  grafana:
    container_name: 'grafana'
    image: 'grafana/grafana'
    restart: 'unless-stopped'
    ports:
      - '3000:3000'
    volumes:
      - './.data/grafana:/var/lib/grafana'

  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus'
    restart: 'unless-stopped'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus:/etc/prometheus'
      - './.data/prometheus:/prometheus'

  blackbox-exporter:
    container_name: 'blackbox-exporter'
    image: 'prom/blackbox-exporter'
    restart: 'unless-stopped'
    ports:
      - '9115:9115'
    volumes:
      - './blackbox-exporter:/etc/blackbox_exporter'

  speedtest-exporter:
    container_name: 'speedtest-exporter'
    image: 'raeffs/speedtest-exporter'
    restart: 'unless-stopped'
    ports:
      - '9112:9112'

  pihole-exporter:
    container_name: 'pihole-exporter'
    image: 'ekofr/pihole-exporter:latest'
    restart: 'unless-stopped'
    ports:
      - '9617:9617'
    environment:
      PIHOLE_HOSTNAME: 'pihole'
      PIHOLE_PASSWORD: 'secure'
      INTERVAL: '30s'
      PORT: '9617'
