http:
  middlewares:
    default:
      chain:
        middlewares:
          - compressd
          - secured
    intranet:
      chain:
        middlewares:
          - local-only
          - default
    secured:
      headers:
        forceSTSHeader: true
        stsPreload: true
        stsSeconds: '315360000'
        stsIncludeSubdomains: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
    compressd:
      compress: {}
    local-only:
      ipWhiteList:
        sourceRange:
          - '127.0.0.1/32'
          - '192.168.1.0/24'
