version: '3.8'

services:
  hello:
    container_name: 'hello'
    build: 'build'
    restart: 'unless-stopped'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.hello.rule=Host(`hello.${DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.hello.entrypoints=websecure'
      - 'traefik.http.routers.hello.tls=true'
      - 'traefik.http.routers.hello.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.hello.tls.domains[0].main=hello.${DOMAIN_SUFFIX}'
      - 'traefik.http.routers.hello.middlewares=default@file'
      - 'traefik.http.services.hello.loadbalancer.server.port=80'
