global:
  scrape_interval: 15s

scrape_configs:
  # pings endpoints
  - job_name: 'icmp-ping'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
        - 'icmp-ping.targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: 'probe_ip_protocol'
        action: drop