version: '3.8'

services:
  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus:latest'
    restart: 'unless-stopped'
    user: 'root'
    volumes:
      - './config/:/etc/prometheus/:ro'
      - '${DATA_DIR:?err}/prometheus/:/prometheus/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_SUFFIX}`)'
      - 'traefik.http.routers.prometheus.entrypoints=websecure'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.prometheus.tls.domains[0].main=prometheus.${DOMAIN_SUFFIX}'
      - 'traefik.http.routers.prometheus.middlewares=intranet@file'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'

  blackbox-exporter:
    container_name: 'blackbox-exporter'
    image: 'prom/blackbox-exporter:latest'
    restart: 'unless-stopped'
    volumes:
      - './config-blackbox-exporter:/etc/blackbox_exporter:ro'

  speedtest-exporter:
    container_name: 'speedtest-exporter'
    image: 'raeffs/speedtest-exporter:latest'
    restart: 'unless-stopped'

  pihole-exporter:
    container_name: 'pihole-exporter'
    image: 'ekofr/pihole-exporter:latest'
    restart: 'unless-stopped'
    environment:
      PIHOLE_HOSTNAME: 'pihole'
      PIHOLE_PASSWORD: '${PIHOLE_PASSWORD}'
      INTERVAL: '30s'
      PORT: '9617'
