log:
  filePath: '/var/log/traefik.log'
  level: 'DEBUG'

providers:
  docker:
    defaultRule: 'Host(`{{ trimPrefix `/` .Name | trimSuffix `-docker-host` }}.home`)'
    exposedByDefault: false
    watch: true
  file:
    directory: '/etc/traefik/dynamic'
    watch: true

api:
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
