tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/home.pem
        keyFile: /etc/certs/home.key
  certificates:
    - certFile: /etc/certs/home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/demo.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/traefik.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/pihole.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/home-assistant.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/phpmyadmin.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/portainer.home.pem
      keyFile: /etc/certs/home.key
